package cs.system.globalization;

@:nativeGen @:libType @:csNative @:native("System.Globalization.NumberFormatInfo") extern final class NumberFormatInfo implements cs.system.ICloneable implements cs.system.IFormatProvider {
	var CurrencyDecimalDigits(get,set) : Int;
	var CurrencyDecimalSeparator(get,set) : String;
	var CurrencyGroupSeparator(get,set) : String;
	var CurrencyGroupSizes(get,set) : cs.NativeArray<Int>;
	var CurrencyNegativePattern(get,set) : Int;
	var CurrencyPositivePattern(get,set) : Int;
	var CurrencySymbol(get,set) : String;
	var DigitSubstitution(get,set) : DigitShapes;
	var IsReadOnly(get,never) : Bool;
	var NaNSymbol(get,set) : String;
	var NativeDigits(get,set) : cs.NativeArray<String>;
	var NegativeInfinitySymbol(get,set) : String;
	var NegativeSign(get,set) : String;
	var NumberDecimalDigits(get,set) : Int;
	var NumberDecimalSeparator(get,set) : String;
	var NumberGroupSeparator(get,set) : String;
	var NumberGroupSizes(get,set) : cs.NativeArray<Int>;
	var NumberNegativePattern(get,set) : Int;
	var PerMilleSymbol(get,set) : String;
	var PercentDecimalDigits(get,set) : Int;
	var PercentDecimalSeparator(get,set) : String;
	var PercentGroupSeparator(get,set) : String;
	var PercentGroupSizes(get,set) : cs.NativeArray<Int>;
	var PercentNegativePattern(get,set) : Int;
	var PercentPositivePattern(get,set) : Int;
	var PercentSymbol(get,set) : String;
	var PositiveInfinitySymbol(get,set) : String;
	var PositiveSign(get,set) : String;
	function new() : Void;
	function Clone() : Dynamic;
	function GetFormat(formatType : cs.system.Type) : Dynamic;
	function get_CurrencyDecimalDigits() : Int;
	function get_CurrencyDecimalSeparator() : String;
	function get_CurrencyGroupSeparator() : String;
	function get_CurrencyGroupSizes() : cs.NativeArray<Int>;
	function get_CurrencyNegativePattern() : Int;
	function get_CurrencyPositivePattern() : Int;
	function get_CurrencySymbol() : String;
	function get_DigitSubstitution() : DigitShapes;
	function get_IsReadOnly() : Bool;
	function get_NaNSymbol() : String;
	function get_NativeDigits() : cs.NativeArray<String>;
	function get_NegativeInfinitySymbol() : String;
	function get_NegativeSign() : String;
	function get_NumberDecimalDigits() : Int;
	function get_NumberDecimalSeparator() : String;
	function get_NumberGroupSeparator() : String;
	function get_NumberGroupSizes() : cs.NativeArray<Int>;
	function get_NumberNegativePattern() : Int;
	function get_PerMilleSymbol() : String;
	function get_PercentDecimalDigits() : Int;
	function get_PercentDecimalSeparator() : String;
	function get_PercentGroupSeparator() : String;
	function get_PercentGroupSizes() : cs.NativeArray<Int>;
	function get_PercentNegativePattern() : Int;
	function get_PercentPositivePattern() : Int;
	function get_PercentSymbol() : String;
	function get_PositiveInfinitySymbol() : String;
	function get_PositiveSign() : String;
	function set_CurrencyDecimalDigits(value : Int) : Int;
	function set_CurrencyDecimalSeparator(value : String) : String;
	function set_CurrencyGroupSeparator(value : String) : String;
	function set_CurrencyGroupSizes(value : cs.NativeArray<Int>) : cs.NativeArray<Int>;
	function set_CurrencyNegativePattern(value : Int) : Int;
	function set_CurrencyPositivePattern(value : Int) : Int;
	function set_CurrencySymbol(value : String) : String;
	function set_DigitSubstitution(value : DigitShapes) : DigitShapes;
	function set_NaNSymbol(value : String) : String;
	function set_NativeDigits(value : cs.NativeArray<String>) : cs.NativeArray<String>;
	function set_NegativeInfinitySymbol(value : String) : String;
	function set_NegativeSign(value : String) : String;
	function set_NumberDecimalDigits(value : Int) : Int;
	function set_NumberDecimalSeparator(value : String) : String;
	function set_NumberGroupSeparator(value : String) : String;
	function set_NumberGroupSizes(value : cs.NativeArray<Int>) : cs.NativeArray<Int>;
	function set_NumberNegativePattern(value : Int) : Int;
	function set_PerMilleSymbol(value : String) : String;
	function set_PercentDecimalDigits(value : Int) : Int;
	function set_PercentDecimalSeparator(value : String) : String;
	function set_PercentGroupSeparator(value : String) : String;
	function set_PercentGroupSizes(value : cs.NativeArray<Int>) : cs.NativeArray<Int>;
	function set_PercentNegativePattern(value : Int) : Int;
	function set_PercentPositivePattern(value : Int) : Int;
	function set_PercentSymbol(value : String) : String;
	function set_PositiveInfinitySymbol(value : String) : String;
	function set_PositiveSign(value : String) : String;
	static var CurrentInfo(get,never) : NumberFormatInfo;
	static var InvariantInfo(get,never) : NumberFormatInfo;
	static function GetInstance(formatProvider : cs.system.IFormatProvider) : NumberFormatInfo;
	static function ReadOnly(nfi : NumberFormatInfo) : NumberFormatInfo;
	static function get_CurrentInfo() : NumberFormatInfo;
	static function get_InvariantInfo() : NumberFormatInfo;
}
